apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: serverapp
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: serverapp
    spec:
      containers:
        - image: 172.1.14.168:5001/judge0-withconf:2
          name: server
          imagePullPolicy: Always
          ports:
            - containerPort: 2358
          resources: {}
          securityContext:
            privileged: true
      restartPolicy: Always
status: {}
