apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - image: 172.1.14.168:5001/judge0-withconf:latest
          name: server
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources: {}
          securityContext:
            privileged: true
      restartPolicy: Always
status: {}
