apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workersapp
  name: workers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workersapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workersapp
    spec:
      containers:
        - args:
            - ./scripts/workers
          image: 172.1.14.168:5001/judge0-withconf:2
          name: workers
          imagePullPolicy: Always
          resources: {}
          securityContext:
            privileged: true
      restartPolicy: Always

status: {}
