apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: workers
  name: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: workers
    spec:
      containers:
        - args:
            - ./scripts/workers
          image: 172.1.14.168:5001/judge0-withconf:latest
          name: workers
          imagePullPolicy: Always
          resources: {}
          securityContext:
            privileged: true
      restartPolicy: Always

status: {}
